apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-z68f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-z68f
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-z68f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-z68f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-z68f
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-haeg-tenant/rhtap-demo-app/hacbs-test-project-z68f@sha256:eb7b90e63ec5b1419657970e4601fc6e4ecc45d855582a2cde6ce014c3019c80
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
